name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Hoặc 'master' nếu đó là nhánh chính

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material

      - name: Build and Deploy
        run: |
          echo "--- Listing files in current directory ---"
          ls -la
          echo "--- Content of mkdocs.yml ---"
          cat mkdocs.yml  # In nội dung của mkdocs.yml mà Action thấy
          echo "--- End of mkdocs.yml content ---"
          echo "--- Running mkdocs gh-deploy with verbose output ---"
          echo "--- Python version ---"
          python --version
          echo "--- MkDocs version ---"
          mkdocs --version
          echo "--- Pip freeze ---"
          pip freeze
          mkdocs gh-deploy --config-file mkdocs.yml --force --verbose
