name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Hoặc 'master' nếu đó là nhánh chính

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material

      - name: Build and Deploy
        run: |
          echo "--- Python version ---"
          python --version
          echo "--- MkDocs version ---"
          mkdocs --version
          echo "--- Pip freeze ---"
          pip freeze # Đảm bảo output này được ghi lại

          echo "--- Listing files in current directory ---"
          ls -la
          echo "--- Content of mkdocs.yml ---"
          cat mkdocs.yml
          echo "--- End of mkdocs.yml content ---"

          echo "--- Running mkdocs build ---"
          mkdocs build --verbose # Chỉ build trang web

          echo "--- Ensuring CNAME file exists in site directory ---"
          # Tạo CNAME thủ công vì mkdocs build không tạo ra nó
          echo "dx-api.truongvietanh.edu.vn" > site/CNAME
          echo "Current content of site/CNAME:"
          cat site/CNAME
          
          echo "--- Deploying to GitHub Pages using ghp-import directly ---"
          # ghp-import sẽ tự động tìm CNAME trong thư mục site/
          # Hoặc bạn có thể chỉ định rõ với cờ -c (xem thêm docs của ghp-import nếu cần)
          ghp-import --no-jekyll -m "Deploy documentation to GitHub Pages" -p site/ -f -b gh-pages
          
          echo "--- Deployment attempt finished. ---"
          echo "Your site should be available at https://dx-api.truongvietanh.edu.vn IF DNS is correctly configured and GitHub Pages has processed the update."
          echo "Check your repository's Pages settings. The 'Custom domain' field should now reflect your domain if deployment was successful."
