name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Hoặc 'master' nếu đó là nhánh chính

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material

      - name: Build and Deploy
        run: |
          echo "--- Python version ---"
          python --version
          echo "--- MkDocs version ---"
          mkdocs --version
          echo "--- Pip freeze ---"
          pip freeze # Hãy đảm bảo output của lệnh này được ghi lại đầy đủ

          echo "--- Listing files in current directory ---"
          ls -la
          echo "--- Content of mkdocs.yml ---"
          cat mkdocs.yml
          echo "--- End of mkdocs.yml content ---"

          echo "--- Running mkdocs build ONLY (verbose) ---"
          mkdocs build --verbose # Chỉ build, không deploy, với output chi tiết

          echo "--- Checking for CNAME file in site directory ---"
          if [ -f site/CNAME ]; then
            echo "CNAME file found in site directory. Content:"
            cat site/CNAME
          else
            echo "CNAME file NOT found in site directory after build."
          fi

          echo "--- Content of site/sitemap.xml (first 5 <loc> tags) ---"
          if [ -f site/sitemap.xml ]; then
            echo "First 5 <loc> tags from site/sitemap.xml:"
            grep "<loc>" site/sitemap.xml | head -n 5
          else
            echo "site/sitemap.xml not found after build."
          fi
          
          echo "--- Intentionally SKIPPING mkdocs gh-deploy for now to analyze build output ---"
          # echo "--- Now running mkdocs gh-deploy ---"
          # mkdocs gh-deploy --config-file mkdocs.yml --force --verbose
