name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main # Hoặc 'master' nếu đó là nhánh chính của bạn

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Hoặc phiên bản Python bạn muốn dùng

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material ghp-import

      - name: Build and Deploy
        run: |
          echo "--- Running mkdocs build ---"
          mkdocs build --verbose # Vẫn giữ verbose để có thông tin nếu build lỗi

          echo "--- Ensuring CNAME file exists in site directory ---"
          # Tạo CNAME thủ công vì mkdocs build 1.6.1 không tự tạo ra nó trong trường hợp này
          echo "dx-api.truongvietanh.edu.vn" > site/CNAME
          echo "Content of site/CNAME:"
          cat site/CNAME
          
          echo "--- Deploying to GitHub Pages using ghp-import directly ---"
          # ghp-import sẽ tự động tìm CNAME trong thư mục site/
          ghp-import --no-jekyll -m "Deploy documentation to GitHub Pages" -p site/ -f -b gh-pages
          
          echo "--- Deployment attempt finished. ---"
          echo "Site should be available at https://dx-api.truongvietanh.edu.vn"